version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - action.destructive_requires_name=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=2s > /dev/null || exit 1"]
      interval: 3s
      timeout: 2s
      retries: 20
      start_period: 5s

  recallm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recallm
    env_file:
      - .env                     # supplies OPENAI_API_KEY
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # Extra resilience (short timeouts so we fail fast if ES ever drops)
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - SPRING_ELASTICSEARCH_CONNECTION-TIMEOUT=2s
      - SPRING_ELASTICSEARCH_SOCKET-TIMEOUT=5s
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - elastic
    restart: on-failure

networks:
  elastic:
    driver: bridge
