services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - action.destructive_requires_name=false
    networks:
      - elastic
    ports:
      - "9200:9200"
      - "9300:9300"

networks:
  elastic:
    driver: bridge
